### ISSUE TITLE
question about "Efficient yet Competitive Speech Translation: FBK@IWSLT2022"

### ISSUE THREAD

**Issue by zhhao1** [hlt-mt/FBK-fairseq#1]
A simple method, char-ratio filter, produce great gains. I've tried it before, but it didn't work out very well. I want to know how you do it and can't find the relevant code. Hopefully you can point out where your code is implemented. There is no file processing flow in the Readme file.

**Comment by mgaido91** [comment]
Thanks for your question. The related code can be found at:

https://github.com/hlt-mt/FBK-fairseq/blob/master/examples/speech_to_text/scripts/filter_on_char_ratio.py.

We will update the README in the next days with your suggestion. Or if you want to create a PR to update it, we appreciate that.

**Comment by mgaido91** [comment]
I'm closing this as I updated the description, now it should be clearer. Please feel free to re-open if something else is needed.

**Comment by zhhao1** [comment]
> I'm closing this as I updated the description, now it should be clearer. Please feel free to re-open if something else is needed.

Sorry for the delay in reply. In the past I didn't remove punctuation from src text, so the filter ratio was set incorrectly. After setting the correct ratio, it will work properly. The updated description is very clear. This is very good work, and I believe that this data processing configuration should be widely used in the future because it is simple, but really effective.

**Comment by mgaido91** [comment]
Thank you for your feedback, and glad it helped. Please let me know if you have other questions.
