### ISSUE TITLE
[Question for AlignAtt] 

### ISSUE THREAD

**Issue by makotos-nlproc** [hlt-mt/FBK-fairseq#5]
Hi, thank you so much for your great work and ope access.

I'd like to reproduce AlignAtt, especially to replicate data preparation and trainig.

Can you provide a guide containing a script or command for data-prepration and traing?

Thanks,

**Comment by mgaido91** [comment]
Hi, thanks for your question. You can follow this README to train the Conformer-based models (without bug related to padding management): https://github.com/hlt-mt/FBK-fairseq/blob/master/fbk_works/BUGFREE_CONFORMER.md.

Please, notice that the models used in the paper were trained with KD from NLLB, which means that you also need to create similar training TSV where in the `tgt_text` column you put the output of NLLB fed with the manual transcripts.

Hope this helps, thanks!

**Comment by mgaido91** [comment]
I am closing this as it has been stale for a while. Feel free to reopen if anything else is needed.
